name: block
description: Bloqueador de apps para seu smartphone.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  floor: 1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: 1.0.1
  build_runner: 1.12.2
flutter:
  uses-material-design: true